# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5a96942aa562f3a601cbda9bb05850bee3744a078e37b6eac9431e7a746a70bda1bde0a448ee49468234dadd4a6887dc2c7d6a609d19609cf33adafa4fdb879f

test:
  secret_key_base: 256d7184fd33a093cda3ddc69c3898c5e86009d8f537249a5945b9e65d91981780d1e59c454e6e449eeb3818aa88c9a731f71ab2ebce3e3255d255ee968341f4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
